project_id = "ismgjjvarzzfsbdpthot"

[functions.nfse-query]
verify_jwt = false

[functions.nfse-emit]
verify_jwt = false

[functions.nfse-download]
verify_jwt = false

[functions.integra-contador]
verify_jwt = false

[functions.cnpj-query]
verify_jwt = false

[functions.classify-segment]
verify_jwt = false

[functions.cnpj-lookup]
verify_jwt = false

[functions.smtp-send]
verify_jwt = false

[functions.classify-document]
verify_jwt = false

[functions.email-track]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = false

[functions.document-public-link]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.nfe-query]
verify_jwt = false

[functions.whatsapp-send-text]
verify_jwt = false

[functions.cert-expiry-alert]
verify_jwt = false
