project_id = "ismgjjvarzzfsbdpthot"

[functions.nfse-query]
verify_jwt = false

[functions.nfse-emit]
verify_jwt = false

[functions.nfse-download]
verify_jwt = false

[functions.integra-contador]
verify_jwt = false

[functions.cnpj-query]
verify_jwt = false

[functions.classify-segment]
verify_jwt = false

[functions.cnpj-lookup]
verify_jwt = false
