UPDATE public.clients SET simples_anexo = CASE main_activity
  WHEN '9602501 - Cabeleireiros, manicure e pedicure' THEN 'III'
  WHEN '5620101 - Fornecimento de alimentos preparados preponderantemente para empresas' THEN 'I'
  WHEN '7319002 - Promoção de vendas' THEN 'III'
  WHEN '9313100 - Atividades de condicionamento físico' THEN 'III'
  WHEN '7490104 - Atividades de intermediação e agenciamento de serviços e negócios em geral, exceto imobiliários' THEN 'V'
  WHEN '8650006 - Atividades de fonoaudiologia' THEN 'V'
  WHEN '5510801 - Hotéis' THEN 'III'
  WHEN '5611204 - Bares e outros estabelecimentos especializados em servir bebidas, sem entretenimento' THEN 'I'
  WHEN '7112000 - Serviços de engenharia' THEN 'V'
  WHEN '2330302 - Fabricação de artefatos de cimento para uso na construção' THEN 'II'
  WHEN '4744001 - Comércio varejista de ferragens e ferramentas' THEN 'I'
  WHEN '4761003 - Comércio varejista de artigos de papelaria' THEN 'I'
  WHEN '4399199 - Serviços especializados para construção não especificados anteriormente' THEN 'IV'
  WHEN '8211300 - Serviços combinados de escritório e apoio administrativo' THEN 'III'
  WHEN '5611201 - Restaurantes e similares' THEN 'I'
  WHEN '3321000 - Instalação de máquinas e equipamentos industriais' THEN 'III'
  WHEN '4771701 - Comércio varejista de produtos farmacêuticos, sem manipulação de fórmulas' THEN 'I'
  WHEN '4729602 - Comércio varejista de mercadorias em lojas de conveniência' THEN 'I'
  WHEN '8121400 - Limpeza em prédios e em domicílios' THEN 'IV'
  WHEN '6821801 - Corretagem na compra e venda e avaliação de imóveis' THEN 'III'
  WHEN '4743100 - Comércio varejista de vidros' THEN 'I'
  WHEN '8599604 - Treinamento em desenvolvimento profissional e gerencial' THEN 'III'
  WHEN '4781400 - Comércio varejista de artigos do vestuário e acessórios' THEN 'I'
  WHEN '5611203 - Lanchonetes, casas de chá, de sucos e similares' THEN 'I'
  WHEN '4520001 - Serviços de manutenção e reparação mecânica de veículos automotores' THEN 'III'
  WHEN '4399103 - Obras de alvenaria' THEN 'IV'
  WHEN '4789005 - Comércio varejista de produtos saneantes domissanitários' THEN 'I'
  WHEN '7319004 - Consultoria em publicidade' THEN 'V'
  WHEN '5611205 - Bares e outros estabelecimentos especializados em servir bebidas, com entretenimento' THEN 'I'
  WHEN '4722902 - Peixaria' THEN 'I'
  WHEN '7420004 - Filmagem de festas e eventos' THEN 'III'
  WHEN '6821802 - Corretagem no aluguel de imóveis' THEN 'III'
  WHEN '4712100 - Comércio varejista de mercadorias em geral, com predominância de produtos alimentícios - minimercados, mercearias e armazéns' THEN 'I'
  WHEN '4322302 - Instalação e manutenção de sistemas centrais de ar condicionado, de ventilação e refrigeração' THEN 'III'
  WHEN '4789004 - Comércio varejista de animais vivos e de artigos e alimentos para animais de estimação' THEN 'I'
  WHEN '4637199 - Comércio atacadista especializado em outros produtos alimentícios não especificados anteriormente' THEN 'I'
  WHEN '4729699 - Comércio varejista de produtos alimentícios em geral ou especializado em produtos alimentícios não especificados anteriormente' THEN 'I'
  WHEN '4723700 - Comércio varejista de bebidas' THEN 'I'
  WHEN '7319003 - Marketing direto' THEN 'V'
  WHEN '4930201 - Transporte rodoviário de carga, exceto produtos perigosos e mudanças, municipal.' THEN 'III'
  WHEN '2511000 - Fabricação de estruturas metálicas' THEN 'II'
  WHEN '5620102 - Serviços de alimentação para eventos e recepções - bufê' THEN 'III'
  WHEN '9601701 - Lavanderias' THEN 'III'
  WHEN '9602502 - Atividades de estética e outros serviços de cuidados com a beleza' THEN 'III'
  WHEN '8650003 - Atividades de psicologia e psicanálise' THEN 'V'
  WHEN '6911701 - Serviços advocatícios' THEN 'IV'
  WHEN '4120400 - Construção de edifícios' THEN 'IV'
  WHEN '9512600 - Reparação e manutenção de equipamentos de comunicação' THEN 'III'
  WHEN '5620104 - Fornecimento de alimentos preparados preponderantemente para consumo domiciliar' THEN 'I'
  WHEN '6920601 - Atividades de contabilidade' THEN 'III'
  WHEN '5590699 - Outros alojamentos não especificados anteriormente' THEN 'III'
  WHEN '4321500 - Instalação e manutenção elétrica' THEN 'III'
  WHEN '4744099 - Comércio varejista de materiais de construção em geral' THEN 'I'
END
WHERE tax_regime = 'simples_nacional'
  AND main_activity IS NOT NULL
  AND (simples_anexo IS NULL OR simples_anexo = '');